#!/bin/sh
#SBATCH --job-name=Job3.1
#SBATCH --output='/nfs/matlabuser/Job3/Task1.log'
#SBATCH --error='/nfs/matlabuser/Job3/Task1.err'
#SBATCH --cpus-per-task=1
#SBATCH --nodelist=compute-0-15,compute-0-16
export MDCE_DECODE_FUNCTION=slurmSimpleDecode
export MDCE_STORAGE_LOCATION=/nfs/matlabuser
export MDCE_STORAGE_CONSTRUCTOR=makeFileStorageObject
export MDCE_JOB_LOCATION=Job3
export MDCE_TASK_LOCATION=Job3/Task1
export MDCE_DEBUG=true
export MATLAB_PREFDIR=/nfs/matlabuser/tmp
'/share/apps/MATLAB/R2014a/bin/worker'  
